---
title: "Data Imporrt"
author: "Rodolfo León"
format: html
editor: visual
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
#| echo: false
suppressPackageStartupMessages(library(tidyverse))
library(ggthemes)

```

```{r}
students <- read_csv("data/students.csv")

```

```{r}
students
```

```{r}
# Force recognition of N/A as NA
students <- read_csv("data/students.csv", na = c("N/A", ""))

students
```

```{r}
students |> 
  rename(
    student_id = `Student ID`, 
    full_name = `Full Name`
  )

students       # Does not work. Better use "janitor".
```

```{r}
students |> janitor::clean_names()  #converts names to snake case all at once
```

```{r}
students <- students |>
  janitor::clean_names() |>
  mutate(
    meal_plan = factor(meal_plan),
    age = parse_number(if_else(age == "five", "5", age))
  )

students
# Should replace "five" with "5" and convert age to dbl but it fails
```

### Exercises

1.  Identify what is wrong with each of the following inline CSV files. What happens when you run the code?

    ```{r}
    readr::read_csv("a,b\n1,2,3\n4,5,6")
    # 2 columns and 3 values. Last 2 get merged
    ```

```{r}
readr::read_csv("a,b,c\n1,2\n1,2,3,4")
# 3 columns and 4 values. Lat 2 get merged.
```

```{r}
readr::read_csv("a,b\n\"1")
# DOes not read rows due to improper syntax
```

```{r}
readr::read_csv("a,b\n1,2\na,b")
# Each column has a numerical and a character value, so the column type is coerced to character:
```

```{r}
readr::read_csv("a;b\n1;3")
# Delimiter ';' is not specified. Gets treated as a whole.
# Fix -> readr::read_delim("a;b\n1;3", quote = "|")
```

```{r}

```

Practice referring to non-syntactic names in the following data frame by:

```{r}
annoying <- tibble(
  `1` = 1:10,
  `2` = `1` * 2 + rnorm(length(`1`))
)
annoying
```

a.  Extracting the variable called `1`.

    ```{r}
    annoying |> select(`1`)
    ```

b.  Plotting a scatterplot of `1` vs. `2`.

    ```{r}
    ggplot(annoying, aes(x = `2`, y = `1`)) +
      geom_point()
    ```

c.  Creating a new column called `3`, which is `2` divided by `1`.

    ```{r}
    annoying |>
      mutate(`3` = `2` / `1`)
    ```

d.  Renaming the columns to `one`, `two`, and `three`.

```{r}
annoying |>
  mutate(`3` = `2` / `1`) |>
  rename(
    "one" = `1`,
    "two" = `2`,
    "three" = `3`
  )
```

```{r}
sales_files <- c(
  "https://pos.it/r4ds-01-sales",
  "https://pos.it/r4ds-02-sales",
  "https://pos.it/r4ds-03-sales"
)
read_csv(sales_files, id = "file")
```

```{r}
sales_files <- c("data/r4ds-01-sales.csv", "data/r4ds-02-sales.csv", "data/r4ds-03-sales.csv")
read_csv(sales_files, id = "file")

```
