---
title: "Workflow: code style"
author: "Rodolfo León"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
#| echo: false
library(tidyverse)
library(ggthemes)
library(nycflights13)
```

Restyle the following pipelines following the guidelines above.

flights\|\>[filter](https://dplyr.tidyverse.org/reference/filter.html)(dest=="IAH")\|\>[group_by](https://dplyr.tidyverse.org/reference/group_by.html)(year,month,day)\|\>[summarize](https://dplyr.tidyverse.org/reference/summarise.html)(n=[n](https://dplyr.tidyverse.org/reference/context.html)(), delay=[mean](https://rdrr.io/r/base/mean.html)(arr_delay,na.rm=TRUE))\|\>[filter](https://dplyr.tidyverse.org/reference/filter.html)(n\>10)

```{r}
flights|>
  filter(dest=="IAH")|>
  group_by(year,month,day)|>
  summarize(
    n=n(),
    delay=mean(arr_delay,na.rm=TRUE))|>
  filter(n>10)
```

flights\|\>filter(carrier=="UA",dest%in%c("IAH","HOU"),sched_dep_time\> 0900,sched_arr_time\<2000)\|\>group_by(flight)\|\>summarize(delay=mean( arr_delay,na.rm=TRUE),cancelled=sum(is.na(arr_delay)),n=n())\|\>filter(n\>10)

```{r}
flights|>
  filter(
    carrier=="UA",
    dest%in%c("IAH","HOU"),
    sched_dep_time> 0900,
    sched_arr_time<2000)|>
  group_by(flight)|>
  summarize(
    delay=mean(arr_delay,na.rm=TRUE),
    cancelled=sum(is.na(arr_delay)),
    n=n()
  )|>
  filter(n>10)
```
